FROM nginx
COPY nginx-app-three.conf /etc/nginx/conf.d/nginx.conf
RUN mkdir /etc/www
COPY app3.html /etc/www/app3.html
RUN chmod 0777 /etc/www/app3.html
RUN chown www-data:www-data /etc/www/app3.html
CMD [ "nginx", "-g", "daemon off;" ]
