FROM nginx
COPY nginx-app-one.conf /etc/nginx/conf.d/nginx.conf
RUN mkdir /etc/www
COPY app1.html /etc/www/app1.html
RUN chmod 0777 /etc/www/app1.html
RUN chown www-data:www-data /etc/www/app1.html
CMD [ "nginx", "-g", "daemon off;" ]
