# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_url = "https://vagrantcloud.com/debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update; apt full-upgrade -y; apt autoremove -y; apt autoclean -y;
    apt install curl selinux-utils policycoreutils gnupg ca-certificates -y;
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt update
    apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    curl -sfL https://get.k3s.io --output k3s.sh;
    chmod 0744 k3s.sh;
    echo "192.168.56.110  tnatonS" >> /etc/hosts;
  SHELL

  config.vm.define "tnatonS" do |tnatonS|
      tnatonS.vm.hostname = "tnatonS"
      tnatonS.vm.network "private_network", ip: "192.168.56.110"
      tnatonS.vm.provider "virtualbox" do |vb|
          vb.name = "tnatonS"
      end
      tnatonS.vm.provision :shell, inline: <<-SHELL
          setenforce permissive
          getenforce
          export K3S_NODE_NAME=tnatonS && \
          export K3S_EXTERNAL_IP=192.168.56.110 && \
          export INSTALL_K3S_EXEC="--flannel-iface=eth1 --tls-san $K3S_EXTERNAL_IP --advertise-address $K3S_EXTERNAL_IP" && \
          /bin/sh k3s.sh ;
          /bin/sh /vagrant/scripts/create-apps.sh ;
        SHELL
  end

end
