apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
  labels:
    app: wil-playground
spec:
  type: ClusterIP
  ports:
    - name: wil-playground
      port: 80
      targetPort: 8888
  selector:
    app: wil-playground
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil-playground
            port:
              number: 80
